export { ActivityBar } from './ActivityBar';
export type { ActivityBarItem, ActivityBarProps } from './ActivityBar';
export {
  WorkbenchArtifactModeControls,
  WorkbenchArtifactPreview,
  WorkbenchArtifactShell,
  formatWorkbenchArtifactContent,
  getWorkbenchArtifactExtension,
  getWorkbenchArtifactTitle,
  getWorkbenchPreviewRenderer,
  getWorkbenchPreviewRendererMatch,
  selectWorkbenchPreviewRenderer,
} from './ArtifactShell';
export type {
  WorkbenchArtifactDescriptor,
  WorkbenchArtifactMode,
  WorkbenchArtifactModeControlsProps,
  WorkbenchArtifactPreviewProps,
  WorkbenchArtifactShellProps,
  WorkbenchArtifactShellRenderCode,
  WorkbenchArtifactShellRenderPreview,
  WorkbenchPreviewRenderer,
  WorkbenchPreviewRendererContext,
  WorkbenchPreviewRendererMatch,
  WorkbenchPreviewRendererMatchReason,
} from './ArtifactShell';
export {
  WorkbenchCommandGroupShell,
  WorkbenchCommandList,
  WorkbenchCommandPalette,
  WorkbenchCommandSuggest,
  commandMenuItemsToWorkbenchCommandDescriptors,
  commandMenuItemToWorkbenchCommandDescriptor,
  filterWorkbenchCommands,
  getNextWorkbenchCommandIndex,
  getWorkbenchCommandExecutionLabel,
  getWorkbenchCommandStatusLabel,
  groupWorkbenchCommands,
  isWorkbenchCommandRunnable,
} from './CommandPalette';
export { WorkbenchMarkdownPreview } from './MarkdownPreview';
export type { WorkbenchMarkdownPreviewProps } from './MarkdownPreview';
export {
  ChatConversationBar,
  ChatHistoryMenu,
  ChatPanel,
  ChatRenameDialog,
  defaultWorkbenchChatConversationLabels,
} from './chat';
export type {
  ChatConversationBarProps,
  ChatHistoryMenuProps,
  ChatPanelProps,
  ChatRenameDialogProps,
  WorkbenchChatConversation,
  WorkbenchChatConversationLabels,
} from './chat';
export { getSlashCommandQuery, isSlashCommandInput, parseSlashCommand } from './chat/slashCommand';
export { useSlashCommandSuggest } from './chat/useSlashCommandSuggest';
export type {
  UseSlashCommandSuggestOptions,
  UseSlashCommandSuggestResult,
} from './chat/useSlashCommandSuggest';
export {
  WORKBENCH_ACTIVE_EDITOR_SAVE_SHORTCUT_ATTRIBUTE,
  hasWorkbenchModalDialogOpen,
  isWorkbenchSaveShortcutEvent,
  useWorkbenchNativeContextMenuGuard,
  useWorkbenchNativeSaveGuard,
} from './keyboard';
export { resolveWorkbenchTheme, useResolvedWorkbenchTheme } from './theme';
export type { ResolvedWorkbenchTheme } from './theme';
export {
  applyWorkbenchAppearance,
  applyWorkbenchThemeAttributes,
  DARK_THEME_PRESET_OPTIONS,
  DARK_THEME_PRESET_MANIFEST,
  DEFAULT_DARK_THEME_PRESET,
  DEFAULT_LIGHT_THEME_PRESET,
  isDarkThemePresetId,
  isLightThemePresetId,
  LIGHT_THEME_PRESET_OPTIONS,
  LIGHT_THEME_PRESET_MANIFEST,
  resolveActiveThemePreset,
  WORKBENCH_COLOR_SCHEME_OPTIONS,
} from './themePresets';
export type {
  DarkThemePresetId,
  LightThemePresetId,
  ThemePresetId,
  WorkbenchAppearanceSettings,
  WorkbenchColorSchemePreference,
  WorkbenchThemeDocumentAttributes,
  WorkbenchThemePresetOption,
  WorkbenchThemePresetManifestEntry,
  WorkbenchThemePresetSelection,
} from './themePresets';
export { WorkbenchThemeProvider } from './WorkbenchThemeProvider';
export type { WorkbenchThemeProviderProps } from './WorkbenchThemeProvider';
export { WorkbenchStoryHost } from './story/WorkbenchStoryHost';
export type { WorkbenchStoryHostProps } from './story/WorkbenchStoryHost';
export {
  WorkbenchShortcutCommandBridge,
  getWorkbenchShortcutCommandBindings,
  getWorkbenchShortcutFromEvent,
  matchesWorkbenchShortcut,
  runWorkbenchShortcutCommand,
  useWorkbenchShortcutCommands,
} from './ShortcutCommandBridge';
export type { SlashCommandParseResult } from './chat/slashCommand';
export type {
  WorkbenchCommandDescriptor,
  WorkbenchCommandDescriptorOverrides,
  WorkbenchCommandExecution,
  WorkbenchCommandFeedback,
  WorkbenchCommandFilterInput,
  WorkbenchCommandGroup,
  WorkbenchCommandGroupBy,
  WorkbenchCommandGroupShellProps,
  WorkbenchCommandGroupingInput,
  WorkbenchCommandListProps,
  WorkbenchCommandNavigationInput,
  WorkbenchCommandOutput,
  WorkbenchCommandPaletteProps,
  WorkbenchCommandRunContext,
  WorkbenchCommandRunSource,
  WorkbenchCommandSideEffect,
  WorkbenchCommandStatus,
  WorkbenchCommandSuggestProps,
} from './CommandPalette';
export type {
  UseWorkbenchShortcutCommandsOptions,
  WorkbenchShortcutCommandBinding,
  WorkbenchShortcutCommandBindingInput,
  WorkbenchShortcutCommandBridgeProps,
  WorkbenchShortcutCommandMissReason,
  WorkbenchShortcutCommandRunInput,
  WorkbenchShortcutCommandRunResult,
  WorkbenchShortcutEventLike,
  WorkbenchShortcutMatchInput,
  WorkbenchShortcutPlatform,
} from './ShortcutCommandBridge';
export {
  WorkbenchConfirmationFlow,
  getWorkbenchConfirmationButtonVariant,
  getWorkbenchConfirmationConfirmLabel,
  getWorkbenchConfirmationSideEffect,
  getWorkbenchConfirmationStatus,
  getWorkbenchConfirmationVariant,
  isWorkbenchConfirmationActionDisabled,
} from './ConfirmationFlow';
export type {
  WorkbenchConfirmationAction,
  WorkbenchConfirmationCancelContext,
  WorkbenchConfirmationCloseContext,
  WorkbenchConfirmationConfirmContext,
  WorkbenchConfirmationContext,
  WorkbenchConfirmationFlowProps,
  WorkbenchConfirmationReason,
  WorkbenchConfirmationSideEffect,
  WorkbenchConfirmationVariant,
} from './ConfirmationFlow';
export {
  WorkbenchAuthGate,
  WorkbenchLoginBrandMark,
  WorkbenchLoginView,
  WorkbenchPasswordResetView,
  WorkbenchSignUpView,
} from './auth';
export type {
  WorkbenchAuthGateProps,
  WorkbenchAuthStatus,
  WorkbenchLoginCredentials,
  WorkbenchLoginSubmitContext,
  WorkbenchLoginViewProps,
  WorkbenchPasswordResetCredentials,
  WorkbenchPasswordResetSubmitContext,
  WorkbenchPasswordResetViewProps,
  WorkbenchSignUpCredentials,
  WorkbenchSignUpSubmitContext,
  WorkbenchSignUpViewProps,
} from './auth';
export { WorkbenchBootstrapGate, WorkbenchBootstrapView, useWorkbenchBootstrap } from './bootstrap';
export type {
  WorkbenchBootstrapController,
  WorkbenchBootstrapGateProps,
  WorkbenchBootstrapRunStatus,
  WorkbenchBootstrapTaskDefinition,
  WorkbenchBootstrapTaskStatus,
  WorkbenchBootstrapTaskViewModel,
  WorkbenchBootstrapViewProps,
} from './bootstrap';
export {
  WORKBENCH_EDITOR_CLOSE_ALL_COMMAND_ID,
  WORKBENCH_EDITOR_CLOSE_COMMAND_ID,
  WORKBENCH_EDITOR_CLOSE_OTHERS_COMMAND_ID,
  WORKBENCH_EDITOR_COPY_PATH_COMMAND_ID,
  WORKBENCH_EDITOR_DELETE_COMMAND_ID,
  WORKBENCH_EDITOR_DISCARD_CHANGES_COMMAND_ID,
  WORKBENCH_EDITOR_SAVE_COMMAND_ID,
  WORKBENCH_EDITOR_SPLIT_DOWN_COMMAND_ID,
  WORKBENCH_EDITOR_SPLIT_RIGHT_COMMAND_ID,
  WORKBENCH_EDITOR_TOGGLE_PINNED_COMMAND_ID,
  WORKBENCH_COMMAND_SURFACE_ACTIVITY_BAR,
  WORKBENCH_COMMAND_SURFACE_EDITOR,
  WORKBENCH_COMMAND_SURFACE_SEARCH,
  WORKBENCH_COMMAND_SURFACE_SETTINGS,
  WORKBENCH_COMMAND_SURFACE_WORKSPACE,
  WORKBENCH_OPEN_SETTINGS_COMMAND_ID,
  WORKBENCH_SEARCH_COPY_RESULT_PATH_COMMAND_ID,
  WORKBENCH_SEARCH_DELETE_RESULT_COMMAND_ID,
  WORKBENCH_SEARCH_OPEN_RESULT_COMMAND_ID,
  WORKBENCH_TOGGLE_PRIMARY_SIDEBAR_COMMAND_ID,
  WORKBENCH_WORKSPACE_COPY_PATH_COMMAND_ID,
  WORKBENCH_WORKSPACE_DELETE_COMMAND_ID,
  WORKBENCH_WORKSPACE_NEW_FILE_COMMAND_ID,
  WORKBENCH_WORKSPACE_NEW_FOLDER_COMMAND_ID,
  WORKBENCH_WORKSPACE_OPEN_COMMAND_ID,
  WORKBENCH_WORKSPACE_RENAME_COMMAND_ID,
  commandMenuItemsToContextMenuItems,
  createWorkbenchEditorCommands,
  createWorkbenchEditorTabListMenuEntries,
  createWorkbenchEditorTabMenuEntries,
  createWorkbenchSearchResultCommands,
  createWorkbenchSearchResultMenuEntries,
  createWorkbenchShellCommands,
  createWorkbenchShellMenuEntries,
  createWorkbenchWorkspaceCommands,
  createWorkbenchWorkspaceCreateMenuEntries,
  createWorkbenchWorkspaceFolderMenuEntries,
  createWorkbenchWorkspaceTargetMenuEntries,
  getWorkbenchShowActivityCommandId,
} from './commands';
export type {
  WorkbenchEditorCommandContext,
  WorkbenchSearchResultCommandContext,
  WorkbenchShellCommandActivity,
  WorkbenchShellCommandContext,
  WorkbenchShellCommandPresetOptions,
  WorkbenchCommandSurface,
  WorkbenchWorkspaceCommandContext,
} from './commands';
export {
  initializeWorkbenchShellState,
  useWorkbenchShellState,
  workbenchShellStateReducer,
} from './shellState';
export type {
  UseWorkbenchShellStateResult,
  WorkbenchShellAction,
  WorkbenchShellInitialState,
  WorkbenchShellState,
} from './shellState';
export {
  getWorkbenchStatusDescriptor,
  getWorkbenchStatusLabel,
  getWorkbenchStatusVariant,
  isWorkbenchStatus,
  isWorkbenchStatusBusy,
  isWorkbenchStatusDisabled,
  isWorkbenchStatusUnavailable,
  workbenchStatusFromLifecycleStatus,
} from './status';
export type { WorkbenchStatus, WorkbenchStatusDescriptor, WorkbenchStatusVariant } from './status';
export { SplitView } from './SplitView';
export type { SplitViewProps } from './SplitView';
export { StatusBar, StatusBarItem, StatusBarSection } from './StatusBar';
export type {
  StatusBarItemModel,
  StatusBarItemProps,
  StatusBarProps,
  StatusBarSectionAlign,
  StatusBarSectionModel,
  StatusBarSectionProps,
} from './StatusBar';
export {
  WorkbenchTimeline,
  WorkbenchTimelineItem,
  formatWorkbenchTimelineMetadataValue,
  getWorkbenchTimelineEventIconClass,
  getWorkbenchTimelineEventLabel,
  getWorkbenchTimelineEventStatus,
  getWorkbenchTimelineMetadataEntries,
} from './Timeline';
export type {
  WorkbenchTimelineEvent,
  WorkbenchTimelineEventKind,
  WorkbenchTimelineItemProps,
  WorkbenchTimelineMessageSource,
  WorkbenchTimelineMetadataEntry,
  WorkbenchTimelineProps,
  WorkbenchTimelineRenderContext,
  WorkbenchTimelineRenderMetadata,
  WorkbenchTimelineRenderPayload,
  WorkbenchTimelineVariant,
} from './Timeline';
export {
  WorkbenchPanelRegion,
  WorkbenchNavigationPanel,
  WorkbenchSectionedPanel,
  WorkbenchSettingsModal,
  WorkbenchStructuredDataForm,
  WorkbenchStructuredDataSchemaFieldInput,
  WorkbenchStructuredDataSchemaPanel,
  WorkbenchStructuredDataSchemaPanelEmbed,
  WorkbenchStructuredDataSchemaPanelFrame,
  WorkbenchStructuredDataTableView,
  WorkbenchStructuredDataTextArrayInput,
  buildWorkbenchStructuredDataTableFromRecords,
  formatWorkbenchStructuredDataTableCell,
} from './settings';
export {
  AccountManagementPanel,
  CommandManagementPanel,
  ExtensionManagementPanel,
  ExtensionManagementSidebar,
  KeybindingManagementPanel,
  ManagementPanelEmptyState,
  ManagementPanelFrame,
  ManagementPanelRunState,
  ManagementPanelSummary,
  ManagementPanelToolbar,
  buildCommandManagementGroups,
  countCommandManagementEntries,
  filterCommandManagementGroups,
  useManagementPanelQuery,
} from './management';
export type {
  AccountManagementEntry,
  AccountManagementEntryStatus,
  AccountManagementPanelProps,
  CommandManagementEntry,
  CommandManagementEntryStatus,
  CommandManagementGroup,
  CommandManagementPanelProps,
  CommandManagementRunState,
  ExtensionCatalogBrowseEntry,
  ExtensionManagementEntry,
  ExtensionManagementPanelProps,
  ExtensionManagementSidebarProps,
  KeybindingManagementPanelProps,
  ManagementPanelFrameProps,
  ManagementPanelToolbarProps,
} from './management';
export type {
  WorkbenchPanelRegionProps,
  WorkbenchNavigationPanelProps,
  WorkbenchSectionedPanelItem,
  WorkbenchSectionedPanelProps,
  WorkbenchSchemaFormCancelContext,
  WorkbenchSchemaFormCheckboxField,
  WorkbenchSchemaFormErrors,
  WorkbenchSchemaFormField,
  WorkbenchSchemaFormFieldBase,
  WorkbenchSchemaFormFieldChangeContext,
  WorkbenchSchemaFormFieldType,
  WorkbenchSchemaFormFieldValue,
  WorkbenchSchemaFormNumberField,
  WorkbenchSchemaFormOption,
  WorkbenchSchemaFormProps,
  WorkbenchSchemaFormSelectField,
  WorkbenchSchemaFormSubmitContext,
  WorkbenchSchemaFormTextField,
  WorkbenchSchemaFormValues,
  WorkbenchSettingsCategory,
  WorkbenchSettingsModalProps,
  WorkbenchSettingsScope,
  WorkbenchStructuredDataFieldType,
  WorkbenchStructuredDataFieldValue,
  WorkbenchStructuredDataFormCancelContext,
  WorkbenchStructuredDataFormCheckboxField,
  WorkbenchStructuredDataFormErrors,
  WorkbenchStructuredDataFormField,
  WorkbenchStructuredDataFormFieldBase,
  WorkbenchStructuredDataFormFieldChangeContext,
  WorkbenchStructuredDataFormNumberField,
  WorkbenchStructuredDataFormOption,
  WorkbenchStructuredDataFormProps,
  WorkbenchStructuredDataFormSection,
  WorkbenchStructuredDataFormSelectField,
  WorkbenchStructuredDataFormSubmitContext,
  WorkbenchStructuredDataFormTextArrayField,
  WorkbenchStructuredDataFormTextField,
  WorkbenchStructuredDataTextArrayInputProps,
  WorkbenchStructuredDataPath,
  WorkbenchStructuredDataRecord,
  WorkbenchStructuredDataSchemaDocument,
  WorkbenchStructuredDataSchemaFieldControl,
  WorkbenchStructuredDataSchemaFieldDefinition,
  WorkbenchStructuredDataSchemaFieldInputProps,
  WorkbenchStructuredDataSchemaPanelClassNames,
  WorkbenchStructuredDataSchemaPanelLabels,
  WorkbenchStructuredDataSchemaPanelProps,
  WorkbenchStructuredDataSchemaPanelEmbedProps,
  WorkbenchStructuredDataSchemaPanelFrameHeaderContent,
  WorkbenchStructuredDataSchemaPanelFrameProps,
  WorkbenchStructuredDataTableViewProps,
  WorkbenchStructuredDataSchemaSectionAliases,
  WorkbenchStructuredDataSchemaSectionSummary,
  WorkbenchStructuredDataSchemaTableColumnInput,
  WorkbenchStructuredDataSchemaTableDefinition,
  WorkbenchStructuredDataSchemaTableRowKeyInput,
  WorkbenchStructuredDataTable,
  WorkbenchStructuredDataTableCellContext,
  WorkbenchStructuredDataTableColumn,
  WorkbenchStructuredDataTableRow,
} from './settings';
export {
  WorkbenchSchemaForm,
  appendWorkbenchStructuredDataSchemaTableRow,
  asWorkbenchStructuredDataRecord,
  booleanWorkbenchStructuredDataSchemaFieldValue,
  coerceWorkbenchStructuredDataFormFieldValue,
  coerceWorkbenchStructuredDataSchemaFieldValue,
  coerceWorkbenchSchemaFormFieldValue,
  createWorkbenchStructuredDataSchemaDocumentEmptyRow,
  createWorkbenchStructuredDataSchemaEmptyRow,
  createWorkbenchStructuredDataSchemaDocumentSampleData,
  createWorkbenchStructuredDataSchemaFallbackSection,
  formatWorkbenchStructuredDataSchemaValue,
  formatWorkbenchStructuredDataSchemaLabel,
  getWorkbenchStructuredDataFormErrors,
  getWorkbenchStructuredDataFormFieldDefaultValue,
  getWorkbenchStructuredDataFormFieldError,
  getWorkbenchStructuredDataFormFields,
  getWorkbenchStructuredDataSchemaDocumentColumnDefinition,
  getWorkbenchStructuredDataSchemaDocumentColumnLabel,
  getWorkbenchStructuredDataSchemaDocumentFieldDefinition,
  getWorkbenchStructuredDataSchemaDocumentFieldLabel,
  getWorkbenchStructuredDataSchemaDocumentPanelData,
  getWorkbenchStructuredDataSchemaDocumentSectionValue,
  getWorkbenchStructuredDataSchemaDocumentSections,
  getWorkbenchStructuredDataSchemaDocumentTableColumns,
  getWorkbenchStructuredDataSchemaDocumentTableDefinition,
  getWorkbenchStructuredDataSchemaFieldDataPath,
  getWorkbenchStructuredDataSchemaFieldControl,
  getWorkbenchStructuredDataSchemaFieldDefaultValue,
  getWorkbenchStructuredDataSchemaFieldDescription,
  getWorkbenchStructuredDataSchemaFieldDefinition,
  getWorkbenchStructuredDataSchemaSectionAnchorId,
  getWorkbenchStructuredDataSchemaSectionId,
  getWorkbenchStructuredDataSchemaSectionPath,
  getWorkbenchStructuredDataSchemaTableCellPath,
  getWorkbenchStructuredDataSchemaTableColumns,
  getWorkbenchStructuredDataSchemaTablePath,
  getWorkbenchStructuredDataSchemaTableRowKey,
  getWorkbenchStructuredDataSchemaTableRows,
  getWorkbenchStructuredDataValue,
  getWorkbenchSchemaFormErrors,
  getWorkbenchSchemaFormFieldDefaultValue,
  getWorkbenchSchemaFormFieldError,
  isWorkbenchStructuredDataFormSubmittable,
  isWorkbenchSchemaFormSubmittable,
  normalizeWorkbenchStructuredDataFormData,
  normalizeWorkbenchSchemaFormValues,
  removeWorkbenchStructuredDataSchemaTableRow,
  setWorkbenchStructuredDataPathOrRootValue,
  setWorkbenchStructuredDataValue,
  slugWorkbenchStructuredDataSchemaAnchor,
  stringifyWorkbenchStructuredDataSchemaFieldValue,
} from './settings';
export { WorkbenchShell } from './WorkbenchShell';
export type { WorkbenchShellProps } from './WorkbenchShell';
export { WorkbenchStandaloneShell } from './WorkbenchStandaloneShell';
export { WorkbenchCanvasShell } from './WorkbenchCanvasShell';
export type {
  WorkbenchStandaloneShellContext,
  WorkbenchStandaloneShellProps,
} from './WorkbenchStandaloneShell';
export type { WorkbenchCanvasShellProps } from './WorkbenchCanvasShell';
export type {
  WorkbenchActivityChangeEvent,
  WorkbenchActivityDescriptor,
  WorkbenchChatController,
  WorkbenchHostCallbackBoundary,
  WorkbenchPatchController,
  WorkbenchSaveController,
  WorkbenchShellContract,
  WorkbenchStandaloneBootstrap,
  WorkbenchStandaloneBootstrapEvent,
  WorkbenchStandaloneEntryState,
  WorkbenchStatusController,
  WorkbenchTheme,
  WorkbenchWorkspaceController,
} from './standalone';
export { StructuredArtifactEditor } from './StructuredArtifactEditor';
export type { StructuredArtifactEditorProps } from './StructuredArtifactEditor';
export type {
  WorkbenchDocument,
  WorkbenchDocumentAdapter,
  WorkbenchDocumentMeta,
  WorkbenchDocumentNode,
  WorkbenchDocumentNodeBase,
  WorkbenchDocumentContainerNode,
  WorkbenchDocumentLeafNode,
  WorkbenchDocumentPatch,
  WorkbenchDocumentPatchOp,
  WorkbenchDocumentRenderContext,
  WorkbenchNodeConstraints,
  WorkbenchNodeLayout,
  WorkbenchNodeType,
  WorkbenchPage,
  WorkbenchVisualStyle,
} from './schema';
export type {
  WorkbenchDocumentPatchError,
  WorkbenchDocumentPatchResult,
  WorkbenchDocumentPatchHistory,
  WorkbenchDocumentPatchHistoryState,
  WorkbenchDocumentAction,
  WorkbenchDocumentActionResult,
  WorkbenchDocumentActionType,
} from './schema';
export {
  applyWorkbenchDocumentPatch,
  createPatchFromWorkbenchDocumentAction,
  assertWorkbenchDocument,
  deserializeWorkbenchDocumentPatch,
  isWorkbenchDocumentSupported,
  initializeWorkbenchDocumentPatchHistory,
} from './schema';
export {
  buildWorkspaceDocumentLookup,
  documentNodesToWorkspaceFiles,
  workspaceFilesToDocument,
} from './schema';
export type {
  WorkspaceToWorkbenchDocumentOptions,
  WorkbenchToWorkspaceConversionOptions,
} from './schema';
export type { WorkbenchDocumentRendererProps } from './schema';
export { WorkbenchDocumentRenderer } from './schema';
